name: dart_app
description: "RizzGuru AI reply assistant."
publish_to: "none"

version: 1.0.0+6

environment:
  sdk: ^3.12.2

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#0D071F"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  cloud_functions: ^5.5.1

  google_sign_in: ^6.2.2

  in_app_purchase: ^3.3.0
  in_app_purchase_android: ^0.5.0

  crypto: ^3.0.7
  http: ^1.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
